version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"

  user-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres

networks:
  wroteit:
    driver: bridge
