apiVersion: apps/v1
kind: Deployment
metadata:
  name: communitiesapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: communitiesapp
  template:
    metadata:
      labels:
        app: communitiesapp
    spec:
      containers:
        - name: communitiesapp
          image: communitiesapp:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: COMMUNITIES_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: COMMUNITIES_URI
