apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificationapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notificationapp
  template:
    metadata:
      labels:
        app: notificationapp
    spec:
      containers:
        - name: notificationapp
          image: notificationapp:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: NOTIFICATIONS_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: NOTIFICATIONS_URI
