apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==
  MONGO_INITDB_ROOT_PASSWORD: ZXhhbXBsZQ==
#  NOTIFICATIONS_URI: bW9uZ29kYjovL3Jvb3Q6ZXhhbXBsZUBsb2NhbGhvc3Q6MjcwMTcvbm90aWZpY2F0aW9ucw==
#mongodb://root:example@mongo:27017/notifications?authSource=admin
  NOTIFICATIONS_URI: bW9uZ29kYjovL3Jvb3Q6ZXhhbXBsZUBtb25nbzoyNzAxNy9ub3RpZmljYXRpb25zP2F1dGhTb3VyY2U9YWRtaW4=
  THREADS_URI: bW9uZ29kYjovL3Jvb3Q6ZXhhbXBsZUBsb2NhbGhvc3Q6MjcwMTcvdGhyZWFkX2Ri
  COMMUNITIES_URI: bW9uZ29kYjovL3Jvb3Q6ZXhhbXBsZUBsb2NhbGhvc3Q6MjcwMTcvY29tbXVuaXRpZXNfZGI=
