apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  NOTIFICATIONS_URI: bW9uZ29kYjovL3Jvb3Q6ZXhhbXBsZUBsb2NhbGhvc3Q6MjcwMTcvbm90aWZpY2F0aW9ucw==
  THREADS_URI: bW9uZ29kYjovL3Jvb3Q6ZXhhbXBsZUBsb2NhbGhvc3Q6MjcwMTcvdGhyZWFkX2Ri
  COMMUNITIES_URI: bW9uZ29kYjovL3Jvb3Q6ZXhhbXBsZUBsb2NhbGhvc3Q6MjcwMTcvY29tbXVuaXRpZXNfZGI=

