apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: dXNlcg==           # base64 for 'user' //TODO
  POSTGRES_PASSWORD: cGFzc3dvcmQ=   # base64 for 'password' //TODO
