apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: dXNlcg==           # base64 for 'user'
  POSTGRES_PASSWORD: cGFzc3dvcmQ=   # base64 for 'password'
  POSTGRES_DB: YXZlcmFnZVNpemVk     # base64 for 'averageSized'
