spring:
  cloud:
    gateway:
      routes:
        - id: userapp
          uri: http://userapp:8080
          predicates:
            - Path=/users/**
        - id: communitiesapp
          uri: http://communitiesapp:8080
          predicates:
            - Path=/communities/**
        - id: communitiesapp
          uri: http://moderationapp:8080
          predicates:
            - Path=/moderators/**
        - id: notificationapp
          uri: http://notificationapp:8080
          predicates:
            - Path=/notifications/**
        - id: threadsapp
          uri: http://threadsapp:8080
          predicates:
            - Path=/threads/**,/votes/**,/comments/**
